[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "mohanad"
authors = [{name = "Mohanad", email = "mohamed@mohanad"}]
dynamic = ["version", "description"]
